---
environmentMode: development
instanceId: BASE
jwtPrivateKey: "<JWT KEY>"
jwtExpiresIn: 86400
mail:
  BrevoAPIKey: "<API KEY>"
  from:
    name: BASE Database
    email: schmida@uni-bonn.de
redisURL: redis://localhost:8482
knex:
  development:
    client: postgresql
    connection:
      host: database
      port: 5432
      database: exomag_base_dev
      user: exomag_base_dev
      password: "<DEV PASSWORD>"
    pool:
      min: 1
      max: 1
    migrations:
      directory: database/migrations
      tableName: knex_migrations
    seeds:
      directory: database/seeds
  production:
    client: postgresql
    connection:
      host: database
      port: 5432
      database: exomag_base_production
      user: exomag_base_production
      password: "<PRODUCTION PASSWORD>"
    pool:
      min: 2
      max: 10
    migrations:
      directory: database/migrations
      tableName: knex_migrations
    seeds:
      directory: database/seeds
